name: "Create release"

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'The name of the artifact to download. Default to no artifact downloaded.'
        required: false
        type: string
      files:
        description: 'Newline-delimited globs of paths to assets to upload for release, must be found in the downloaded artifact.'
        required: false
        type: string

jobs:
  create_release:
    name: Create from merged release branch
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from branch name
        id: extract-version
        shell: python
        run: |
          branch_name = "${{ github.event.pull_request.head.ref }}"
          version = branch_name.split("/")[1]

          print(f"::set-output name=version::{version}")

      - name: Extract changelog section for release
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          version: ${{ steps.extract-version.outputs.version }}

      - name: Download artifacts for release
        if: ${{ inputs.artifact_name }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v0.1.13
        with:
          name: ${{ steps.extract-version.outputs.version }}
          tag_name: ${{ format('v{0}', steps.extract-version.outputs.version) }}
          fail_on_unmatched_files: ${{ inputs.artifact_name }}
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.description }}
          target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
          files: ${{ inputs.files }}
