name: "Draft new release"

on:
  workflow_call:
    inputs:
      version:
        description: 'The new version in major.minor.patch format.'
        required: true
        type: string
      build:
        description: 'Build the projet with cargo, useful when Cargo.lock is commited and needs to be updated.'
        required: false
        default: false
        type: boolean
      check_publish:
        description: 'Dry run cargo publish before pushing changes, useful to not allow unpublishable releases.'
        required: false
        default: false
        type: boolean
      base_branch:
        description: 'Defines the base branch to use to create the pull request against. Default to main.'
        required: false
        default: 'main'
        type: string

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create release branch
        run: git checkout -b release/${{ inputs.version }}

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: ${{ format('v{0}', inputs.version) }}
          changelogPath: CHANGELOG.md

      - name: Bump version in Cargo.toml
        uses: thomaseizinger/set-crate-version@1.0.0
        with:
          version: ${{ github.event.inputs.version }}
          manifest: Cargo.toml

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cargo build update lockfile
        if: ${{ inputs.build }}
        run: cargo build

      - name: Format CHANGELOG
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          /home/runner/.dprint/bin/dprint fmt CHANGELOG.md

      - name: Publish dry run
        if: ${{ inputs.check_publish }}
        run: cargo publish --dry-run --allow-dirty

      - name: Add, Commit & Push
        id: make-commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          default_author: github_actions
          message: Prepare release ${{ github.event.inputs.version }}
          new_branch: release/${{ github.event.inputs.version }}
          push: origin release/${{ github.event.inputs.version }} --set-upstream --force

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.2.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ github.event.inputs.version }}
          base: ${{ inputs.base_branch }}
          title: Release version ${{ github.event.inputs.version }}
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit_sha }}.

            Merging this PR will create a GitHub release and may update the library/binary on crates.io!
